/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "(Lvl": "(等级",
    "Armor": "护甲",
    "ATK:": "攻击:",
    "Attack:": "攻击:",
    "Defense:": "防御:",
    "Attack": "攻击",
    "ATK:": "攻击:",
    "DEF:": "防御:",
    "Health:": "生命值:",
    "Intelligence:": "智力:",
    "Auto-Recycle:": "自动回收:",
    "Base Defense": "基础防御",
    "Base Attack": "基础攻击",
    "Base Intelligence": "基础智力",
    "Base Max Health": "基础生命值上限",
    "Buy": "购买",
    "Cancel": "取消",
    "Combat Log": "战斗日志",
    "Idle Realms": "领域放置",
    "Inventory": "库存",
    "Level": "等级",
    "Mana": "法力",
    "Quests": "任务",
    "Rebirth": "重生",
    "Training": "训练",
    "Slime": "史莱姆",
    "Zone Control": "区域控制",
    "Zone Boss": "区域Boss",
    "Yes, Reset": "是的, 重置",
    "Weapon": "武器",
    "Upgrades": "升级",
    "Time Played:": "游戏时长:",
    "The Quest System": "任务系统",
    "Empty": "空",
    "Complete your first rebirth to unlock the quest system and begin your journey of discovery": "完成你的第一次重生来解锁任务系统，开始你的发现之旅。",
    "Confirm Game Reset": "确认游戏重置",
    "Defeat the zone boss to unlock the next area": "击败区域Boss解锁下一个区域。",
    "Energy Capacitor": "能量电容器",
    "Energy Conduit": "能量管道",
    "Equipment": "装备",
    "Leaderboard": "排行榜",
    "Adventure": "冒险",
    "Reset Game": "重置游戏",
    "Class": "职业",
    "Defense": "防御",
    "Health": "生命值",
    "Intelligence": "智力",
    "Navigation": "导航",
    "Player Stats": "玩家属性",
    "Training Grounds": "训练场",
    "Vagrant": "流浪者",
    "": "",
    "Spend Energy from your pool to passively train your stats. A higher energy generation rate allows for faster training, while a larger capacity allows for more offline progress": "从你的池中消耗能量来被动地训练你的属性。更高的能量产生率允许更快的训练，而更大的容量允许更多的离线进展",
    "All equipment provides better stats": "所有装备提供更好的属性",
    "Ancient Knowledge": "古代知识 ",
    "Essence": "精华 ",
    "Essence Attunement": "精华调和 ",
    "Essence can be used to purchase powerful permanent upgrades that persist through all future Rebirths": "精华可以用来购买强大的永久升级，持续到所有未来的重生",
    "Essence Upgrades": "精华升级 ",
    "Fortune's Favor": "天命眷顾 ",
    "Gain more EXP from all sources": "从所有资源中获得更多经验 ",
    "Increases the chance for monsters to drop higher rarity loot": "增加怪物掉落稀有物品的几率",
    "Increases the chance of finding higher rarity items": "增加找到稀有物品的机会",
    "Master Smithing": "锻冶大师 ",
    "Next Lvl:": "下一级： ",
    "Permanently increases training speed": "永久提高训练速度",
    "Rebirth allows you to start over, but with newfound power. You will reset your Level, Gold, Upgrades, and Zone progress in exchange for": "重生可以让你重新开始，拥有新的力量。你将重置你的等级，金币，升级和区域进度作为交换 ",
    "Rebirth Locked": "重生未解锁 ",
    "Rebirths:": "重生： ",
    "Reduces physical damage taken from monsters": "减少怪物的物理伤害",
    "Required Zone to Unlock:": "需要解锁的区域： ",
    "Start each new life with a lump sum of Gold": "用一笔金币开始每一次新生活",
    "Start each new life with some Gold": "用一些金币开始新的生活",
    "Sunken Grotto": "沉没石窟 ",
    "Swift Training": "快速训练 ",
    "The Altar of Rebirth": "重生祭坛 ",
    "You must prove your worth by reaching your fated destination for this life": "你必须通过达到你此生命中注定的目标来证明你的价值。",
    "Energy is used to passively train your stats on the Training screen. It regenerates over time": "能量用于被动地训练你在训练界面上的属性。它会随着时间的推移而再生",
    "Essence is a permanent currency earned by Rebirthing. Use it for powerful upgrades that persist through all playthroughs": "精华是通过重生获得的永久货币。将其用于所有游戏过程中持续存在的强大升级",
    "Gold is earned from defeating monsters and is used to buy temporary upgrades, skills, and spells for your current run": "金币是通过打败怪物获得的，可以用来购买临时升级、技能和法术",
    "Increases the power of your magical skills and spells. Also slightly increases mana regeneration": "增加你的魔法技能和法术的力量。也稍微增加法力回复。",
    "🏆 Demon King Defeats - Personal Records": "🏆 恶魔之王击败 - 个人记录 ",
    "All progress will be permanently lost": "所有进度将永久丢失",
    "Are you sure you want to reset your game?": "你确定要重置游戏吗？ ",
    "Defeat the Demon King to earn your first entry": "击败魔王获得你的第一条记录",
    "No victories yet!": "暂无胜利！ ",
    "Your fastest times defeating the Demon King at each rebirth level. This leaderboard is permanent and persists through all resets": "在每个重生关卡中以最快的速度击败魔王。这个排行榜是永久性的，并在所有重置中持续存在。",
    "\"Some mysteries can only be seen by those who have walked the path before...\"": "“有些秘密只有那些曾经走过这条路的人才能看到……” ",
    "A peaceful field, but strange creatures have been spotted lately..": "一片宁静的田野，但最近发现了奇怪的生物…… ",
    "Accessory": "配饰 ",
    "Whispering Meadows": "细语草甸 ",
    "Bigger. Jigglier": "更大。摇摇欲坠",
    "Boosts the rate at which you gain Energy": "提高你获得能量的速度",
    "Challenge Boss": "挑战Boss ",
    "Equipped Gear": "已穿戴装备 ",
    "Fight Monsters": "对抗怪物 ",
    "Improves training efficiency. Get more stats for each point of Energy spent": "提升训练效率每消耗一点能量就获得更多的属性",
    "Improves training speed but also increases its Energy cost": "提高训练速度，但也增加了能量消耗",
    "Increases your base Maximum Health": "增加你的基础最大生命值",
    "Increases your maximum Energy storage": "增加你的最大能量储存",
    "It's just a blob": "只是一团而已",
    "King Slime": "史莱姆国王 ",
    "Neural Amplifier": "神经放大器 ",
    "Next Zone": "下一个区域 ",
    "Previous Zone": "前一个区域 ",
    "Recycle weaker items automatically": "自动回收较弱的物品",
    "Reinforced Vigor": "增强活力 ",
    "Spend Gold to purchase permanent upgrades": "使用金币购买永久升级",
    "Your inventory is empty. Defeat monsters to find loot!": "你的库存是空的。击败怪物获得战利品！",
    "Boosts Energy generation per second. Speeds up all training": "提高能量生成每秒。加速所有训练。",
    "Equip": "装备",
    "Farmer's Pitchfork": "农民的干草叉",
    "Forest Sprite": "森林精灵",
    "Gnarled Staff": "粗糙的手杖",
    "Leather Tunic": "皮革束腰外衣",
    "LEVEL UP!": "升级了！",
    "Looking for an easy purse": "找一个方便的钱包。",
    "Mischievous woodland spirit": "淘气的森林精灵。",
    "Roadside Bandit": "路边强盗",
    "Rusty Sword": "生锈的剑",
    "Sell All (": "全部出售(",
    "Stats": "统计数据",
    "Stop Fighting": "停止战斗",
    "Surprisingly aggressive": "惊人的攻击性。",
    "Unequip": "卸下装备",
    "Wild Boar": "野猪",
    "You reached level": "你达到了等级",
    "Lucky Charm": "幸运符",
    "Crimson Peaks": "深红山峰",
    "Apprentice's Robe": "学徒长袍",
    "Continue..": "继续. .",
    "Crude, but effective magic": "粗糙但有效的魔法",
    "Eagle Amulet": "雄鹰护身符",
    "Flee Battle": "逃离战斗",
    "Goblin Cleaver": "哥布林切刀",
    "Goblin Scout": "哥布林斥候",
    "Goblin Warlord": "哥布林战神",
    "Goblin Warrior": "哥布林战士",
    "He's got a bigger axe": "他有一把更大的斧头",
    "Hobgoblin Shaman": "妖怪萨满",
    "Hungry and fast": "又饿又快",
    "Iron Sword": "铁剑",
    "Mountain Wolf": "山狼",
    "Rocky crags echo with the war cries of goblin tribes": "岩石峭壁上回荡着半兽人部落的战争呐喊",
    "Small and sneaky": "小而狡猾",
    "The boss of this zone has been defeated!": "该区域首领已被击败！",
    "The way forward is open. Advance to the next zone when you are ready": "前进的道路是开放的。准备好后进入下一个区域",
    "Wields a rusty axe": "挥舞着一把生锈的斧头",
    "A damp, phosphorescent cave system filled with amphibious terrors": "潮湿的磷光洞穴系统充满了两栖动物的恐怖",
    "Coral Trident": "珊瑚三叉戟",
    "Crackles with static": "静电裂纹",
    "Eel Swarm": "鳗鱼群",
    "Even as a baby, it's huge": "即使是婴儿，它也是巨大的",
    "Giant Crab": "巨蟹",
    "Gurgles menacingly": "发出威胁的咯咯声",
    "Hexes from the mire": "来自泥潭的咒语",
    "Iron Plate": "铁板",
    "Leviathan Hatchling": "利维坦幼体",
    "Murloc Forager": "穆洛克觅食者",
    "Scale Mail": "鳞甲锁甲",
    "Snip snip": "咔嚓咔嚓",
    "Swamp Witch": "沼泽女巫",
    "Barnacle Club": "藤壶狼牙棒",
    "Crusher's Mace": "破碎机的权杖",
    "Pearl of Wisdom": "智慧珍珠",
    "Tidal Scepter": "潮汐权杖",
    "Are you sure you want to Rebirth? You will gain": "你确定要重生吗？你会得到",
    "but your progress will be reset (level, gold, upgrades, equipment)": "但是你的进度会被重置（等级，金币，升级，装备）",
    "Cinderfall Volcano": "灰落火山",
    "Confirm Rebirth": "确认重生",
    "Next Rebirth will grant:": "下次重生将获得：",
    "Not Yet": "还没有",
    "Perform Rebirth": "进行重生",
    "Permanently increases all EXP gained, speeding up leveling in future runs": "永久增加所有获得的经验，加速升级在未来的运行",
    "Rebirth!": "重生!",
    "Skills": "技能",
    "Your character level. Leveling up increases your base stats and unlocks new capabilities": "你的角色等级。升级可以增加你的基本属性并解锁新的能力",
    "(Cost:": "(成本:",
    "Arcane Bolt": "奥术弩箭",
    "Find more gold from monsters": "从怪物身上找到更多的金币",
    "Gain more EXP from monsters": "从怪物身上获得更多的经验",
    "General Spells": "通用法术",
    "Increases mana regeneration": "增加法力回复",
    "Increases max health": "增加生命值上限",
    "Meditation": "冥想",
    "Passively hurl bolts of raw magic at your foe, consuming mana to deal damage based on your Intelligence": "被动地向你的敌人投掷原始魔法，消耗法力值以造成基于你智力的伤害",
    "Quick Learner": "快速学习者",
    "Scrounge": "搜刮",
    "Skills & Spells": "技能&法术",
    "Spend Gold and Energy to learn and upgrade powerful abilities. Skills and spells are reset upon Rebirth": "花费金币和能量来学习和升级强大的技能。技能和法术在重生时重置",
    "Survivalist": "生存主义者",
    "Increases your total health pool, allowing you to survive more damage": "增加你的总血量，使你能承受更多的伤害",
    "Iron Spear": "铁矛",
    "Upgrade": "升级",
    "Woodcutter's Axe": "樵夫的斧头",
    "You": "你",
    "You have been defeated!": "你被打败了！",
    "\"The journey of discovery begins with a single step into the unknown...\"": "“发现之旅始于向未知迈出的第一步……”",
    "Explore the world and defeat zone bosses to discover mysterious quests": "探索世界，击败区域boss，发现神秘的任务",
    "No Quests Completed Yet": "暂无任务完成",
    "Quest Overview": "任务概述",
    "Quest Points": "任务点数",
    "Quests Completed": "完成的任务",
    "Titles Unlocked": "已解锁称号",
    "Your current character class, which determines available skills and stat specializations": "你当前的角色职业，它决定了可用的技能和属性专长",
    "Your Quest Journal": "你的任务日志",
    "In the dirt near the fallen boss, you notice something unusual. The ground is pressed with round, heavy footprints — the shape is too perfect, too even. No beast could have left these marks. They look as though they were stamped into the ground by something built, not born": "在倒地首领附近的泥土中，你发现了一些不寻常的东西。地上满是又圆又重的脚印——形状太完美，太均匀了。这些痕迹是野兽不可能留下的。它们看起来就像被建造起来的东西踩在地上的，而不是天生的",
    "• Title unlocked:": "• 解锁称号：",
    "Accept Reward": "接受奖励",
    "Continue your journey forward": "继续你的旅程",
    "Rewards:": "奖励:",
    "The First Print": "第一个印记",
    "Trail-Spotter": "追踪者",
    "What to do next:": "接下来该怎么做：",
    "• Title:": "• 称号:",
    "✓ COMPLETED": "✓ 已完成",
    "Collected Titles": "已收集称号",
    "Completed Quests": "已完成任务",
    "Title": "称号",
    "REWARDS OBTAINED:": "获得奖励",
    "• Badge unlocked:": "• 解锁的徽章:",
    "• Badge:": "• 徽章:",
    "More footprints appear deeper in the land. This time, there are two sets. One stride is steady and strong. The other drags slightly, as if limping. Whatever leaves these tracks is not traveling alone. The mystery grows heavier with every step you take": "更多的脚印出现在陆地的深处。这一次，有两组。一步稳，一步强。另一条腿稍微拖了一下，好像一瘸一拐的。留下这些痕迹的东西不是一个人在旅行。你每走一步，神秘感就越重",
    "Are you sure you want to sell all items in your inventory?": "你确定要卖掉库存中的所有物品吗？",
    "Badge": "徽章",
    "Collected Badges": "收集的徽章",
    "Dust-Marked": "布满灰尘",
    "gold": "黄金",
    "Keep Items": "保留物品",
    "Press on to the next challenge": "继续下一个挑战",
    "Sell All": "出售所有",
    "Sell All Items": "出售所有物品",
    "The Heavy Step": "沉重的步伐",
    "This action cannot be undone!": "此操作无法撤销！",
    "You will receive": "你会收到",
    "The trail changes. The footprints are burned into the stone, edges scorched as though fire had licked across the ground. Whoever passed here was moving fast, and with great weight. The prints lead further ahead, daring you to follow": "路线改变了。脚印刻在石头上，边缘烧焦了，好像火舔过地面。从这里经过的人走得很快，而且很重。脚印一直延伸到更远的地方，让你不敢跟随",
    "A being of pure flame": "纯净的火焰",
    "A flickering, angry pixel": "一个闪烁、愤怒的像素",
    "A reality of broken code and digital phantoms. Nothing is as it seems": "现实中充斥着破碎的代码和数字幻影。没有什么是表面看起来的那样",
    "A sentient, god-like AI": "一个有感情的，像上帝一样的人工智能",
    "Access denied": "拒绝访问",
    "Ancient Phoenix": "上古凤凰",
    "Ash Drake": "灰龙",
    "Bugged Knight": "窃听骑士",
    "Corrupted Sprite": "损坏的精灵",
    "Data-Stream Katana": "数据流武士刀",
    "Ember Robes": "余烬长袍",
    "Fire Elemental": "火元素",
    "Firewall Sentry": "防火墙哨兵",
    "Glitch Ghoul": "故障食尸鬼",
    "Inferno Staff": "地狱之杖",
    "Keep chasing the trail deeper into danger": "继续追着线索，越追越危险",
    "Lava Serpent": "熔岩蛇",
    "Magma Golem": "岩浆傀儡",
    "Magma-Forged Plate": "岩浆锻造甲片",
    "Molten rock given life": "熔岩赋予生命",
    "Null reference exception": "空引用异常",
    "Null-Pointer Halberd": "空指针戟",
    "Obsidian Blade": "黑曜石刃",
    "Phases between frames": "帧间相位",
    "Reborn in fire, over and over": "在火中重生，一次又一次",
    "Sinuous, searing heat": "弯曲的，灼热的热",
    "The air is thick with ash and the ground sizzles beneath your feet": "空气中弥漫着厚厚的火山灰，脚下的地面嘶嘶作响",
    "The Glitched Matrix": "故障矩阵",
    "The Mainframe": "主机",
    "The Pursuit": "追击之卷",
    "Trail-Chaser": "追踪者",
    "Whelp of a greater beast": "更大野兽的幼崽",
    "You fled from battle": "你逃离了战斗",
    "In the boss's lair you uncover a battered brass buckle, half-buried in the dust. As you pick it up, you realize the truth: the stride, the depth, the weight — they are your own footprints. Somehow, your path is being marked before you walk it, as if the world already knows the steps you will take. The mystery has only just begun": "在Boss的老窝里，你发现了一个半埋在尘土里的破旧的铜扣。当你把它捡起来的时候，你意识到一个事实：它的步幅、深度、重量——它们都是你自己的脚印。不知怎的，在你走之前，你的道路就已经被标记好了，好像世界已经知道你将要走的每一步。谜底才刚刚揭开",
    "A beast made of starlight": "一个由星光组成的野兽",
    "A form that defies geometry": "一种无视几何的形式",
    "Aethel, the Star-Eater": "噬星者艾塞尔",
    "An abandoned tower where the cosmos bleeds into reality": "一座废弃的塔，在那里宇宙融入了现实",
    "Astral Knight": "星辰骑士",
    "Celestial Scepter": "天杖",
    "Comet Spear": "彗星矛",
    "Cosmic Horror": "宇宙恐怖",
    "Fallen Constellation": "陨落星座",
    "Firewall Armor": "防火墙护甲",
    "Galaxy Shard": "星系碎片",
    "It consumes dying suns": "它吞噬垂死的太阳",
    "Loopwalker": "环行者",
    "Rebirth to lock in what you've learned": "重生来锁定你所学到的东西",
    "Shines with distant suns": "闪耀着遥远的太阳",
    "Slips between seconds": "秒间滑动",
    "Starfall Observatory": "星落天文台",
    "The Truth in the Sand": "沙子里的真相",
    "Time Wisp": "时间精灵",
    "Start Your Adventure": "开始你的冒险",
    "Train your stats, defeat powerful monsters, and collect legendary loot. When you grow strong enough, challenge the zone's boss to unlock new regions. But your path does not end there. Through the power of Rebirth, you can sacrifice your progress to gain permanent power, unlocking new skills and classes to reach even greater heights. Your ultimate goal: to conquer all realms and defeat the Demon King himself": "训练你的属性，击败强大的怪物，并收集传奇战利品。当你变得足够强大时，挑战区域的boss来解锁新的区域。但你的道路并没有就此结束。通过重生的力量，你可以牺牲你的进度来获得永久的力量，解锁新的技能和职业，达到更高的高度。你的最终目标是：征服所有的王国，打败魔王本人",
    "Your progress is saved automatically in your browser": "您的进度将自动保存在浏览器中",
    "Welcome, adventurer, to a realm of endless progression. Your journey will take you through enchanted lands, from whispering meadows to the fiery heart of a volcano": "欢迎你，冒险家，来到一个永无止境的世界。您的旅程将带您穿越迷人的土地，从低语的草地到炽热的火山中心",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "_": "_",
    "🎉": "🎉",
    "\"": "\"",
    "%": "%",
    "/": "/",
    "+": "+",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "EXP: ": "经验值: ",
    "Max HP: ": "生命值上限: ",
    "INT: ": "智力: ",
    "attack: ": "攻击: ",
    "defense: ": "防御: ",
    "Loot! Found ": "战利品！找到了",
    "Adventure: ": "冒险: ",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    ".": ".",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+) \/ ([\d\.]+)K$/,
    /^([\d\.]+)K \/ ([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^You venture into the (.+)..$/, '你冒险进入了 $1..'],
    [/^Auto-recycled (.+) for (.+) gold$/, '自动回收 $1 获得了 $2 金币'],
    [/^You defeated (.+)!$/, '你击败了 $1!'],
    [/^Gained (.+) EXP and (.+) Gold$/, '获得了 $1 经验值和 $2 金币'],
    [/^You hit (.+) for (.+) damage$/, '你击中了 $1 并对其造成了 $2 伤害'],
    [/^(.+) hits you for (.+) damage$/, '$1 击中了并对你造成了 $2 伤害'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) Max Energy$/, '\+$1 能量上限'],
    [/^\+([\d\.]+) Max Health$/, '\+$1 生命值上限'],
    [/^\+([\d\.]+) Starting Gold$/, '\+$1 初始金币'],
    [/^\+([\d\.]+) Quest Points$/, '\+$1 任务点数'],
    [/^\+([\d\.]+)\% Training Speed \/ \+([\d\.]+)\% Energy Cost$/, '\+$1\% 训练速度 \/ \+$2\% 能量成本'],
    [/^\+([\d\.]+)\% Training Speed$/, '\+$1\% 训练速度'],
    [/^\+([\d\.]+)\% XP Gain$/, '\+$1\% 经验值增益'],
    [/^\+([\d\.]+)\% Gold Gain$/, '\+$1\% 金币增益'],
    [/^\+([\d\.]+)\% Energy Gain$/, '\+$1\% 能量增益'],
    [/^\+([\d\.]+)\% INT to damage$/, '\+$1\% 智力到伤害'],
    [/^\+([\d\.]+)\% Maximum Health$/, '\+$1\% 生命值上限'],
    [/^\+([\d\.]+)\% Max Health$/, '\+$1\% 生命值上限'],
    [/^\+([\d\.]+)\% Mana Regen$/, '\+$1\% 法力回复'],
    [/^\+([\d\.]+)\% Attack$/, '\+$1\% 攻击'],
    [/^\+([\d\.]+)\% Gold$/, '\+$1\% 金币'],
    [/^\+([\d\.]+)\% EXP$/, '\+$1\% 经验值'],
    [/^\+([\d\.]+)\% EXP Gain$/, '\+$1\% 经验增益'],
    [/^\+([\d\.]+)\% Better Loot Chance$/, '\+$1\% 更好的战利品几率'],
    [/^\+([\d\.]+)\% Equipment Stats$/, '\+$1\% 装备属性'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);